persistence : "mySqlUnit"

repository : 
  client : database
  compte : database
  article : database
  dette : database
  detail : database
  demande : database
  detailDemande : database
  paiement : database